name: Deploy Live Update
on:
  push:
    branches:
      - main
jobs:
  uplaod-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build web assets
        run: cd my-app/ && yarn build
