name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd my-app && npm install -g yarn
      - run: cd my-app && yarn install --frozen-lockfile
      - run: cd my-app && yarn build
