name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: Deploy Live Update
        uses: capawesome-team/cloud-live-update-action@v0.0.1
        id: upload-action
        with:
          appId: '137658f6-588e-41d3-a46b-00488a5fc878'
          channel: 'production-1.0.0'
          path: 'out'
          token: ${{ secrets.CAPAWESOME_TOKEN }}
